name: Spring Boot CD

on:
  push:
    branches: ['main']

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: JDK 21 설정
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Gradle 설정
        uses: gradle/actions/setup-gradle@v4

      - name: Gradle 실행 권한 부여
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew build -x test

      - name: FEESH_BACK CD Discord Notification (success)
        if: ${{ success() }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_BACK_WEBHOOK }}
          status: ${{ job.status }}
          title: '✅ 성공 ✅'
          description: '서버 배포 성공 '
          color: 65280
          username: 'FEESH-BACK-bot'

      - name: FEESH_BACK CD Discord Notification (failure)
        if: ${{ failure() }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_BACK_WEBHOOK }}
          status: ${{ job.status }}
          title: '❗️ 실패 ❗️'
          description: '서버 배포 실패'
          color: 16711680
          username: 'FEESH-BACK-bot' 